"""create patient cost

Revision ID: 12b410cfeb8b
Revises: 79621abdd49e
Create Date: 2025-03-04 13:26:48.376558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b410cfeb8b'
down_revision: Union[str, None] = '79621abdd49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_cost',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('total_cost', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'month', name='unique_patient_month')
    )
    op.create_index(op.f('ix_patient_cost_id'), 'patient_cost', ['id'], unique=False)
    op.create_index(op.f('ix_patient_cost_patient_id'), 'patient_cost', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_cost_patient_id'), table_name='patient_cost')
    op.drop_index(op.f('ix_patient_cost_id'), table_name='patient_cost')
    op.drop_table('patient_cost')
    # ### end Alembic commands ###
