"""create cost of medical record

Revision ID: 79621abdd49e
Revises: daad115c7649
Create Date: 2025-03-04 08:49:06.826250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79621abdd49e'
down_revision: Union[str, None] = 'daad115c7649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_record', sa.Column('cost', sa.DECIMAL(precision=65, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_record', 'cost')
    # ### end Alembic commands ###
